const questionData = {
    cyber: {
        offensive: [
            { id: 1, question: "What is the primary goal of penetration testing?", options: ["To exploit systems for financial gain", "To simulate attacks and identify vulnerabilities before real attackers do", "To install security patches", "To monitor network traffic"], correctAnswer: 1 },
            { id: 2, question: "Which phase involves gathering information without touching the target system?", options: ["Scanning", "Exploitation", "Passive Reconnaissance", "Post-Exploitation"], correctAnswer: 2 },
            { id: 3, question: "What does SQL Injection allow an attacker to do?", options: ["Crash a web server", "Execute arbitrary SQL commands against a database", "Intercept network packets", "Brute-force passwords"], correctAnswer: 1 },
            { id: 4, question: "What tool is commonly used for network port scanning?", options: ["Wireshark", "Metasploit", "Nmap", "John the Ripper"], correctAnswer: 2 },
            { id: 5, question: 'What is a "zero-day" vulnerability?', options: ["A vulnerability with no patch available yet", "A vulnerability discovered on January 1st", "A vulnerability that has been patched", "A vulnerability in very old software"], correctAnswer: 0 },
            { id: 6, question: "Which attack intercepts communication between two parties without their knowledge?", options: ["DDoS", "Man-in-the-Middle (MitM)", "Phishing", "Rootkit"], correctAnswer: 1 },
            { id: 7, question: 'What is "privilege escalation"?', options: ["Installing antivirus software", "Gaining higher access rights than originally assigned", "Encrypting user files", "Scanning for open ports"], correctAnswer: 1 },
            { id: 8, question: "What does XSS (Cross-Site Scripting) enable an attacker to do?", options: ["Bypass firewall rules", "Inject client-side scripts into web pages viewed by others", "Perform a DDoS attack", "Crack password hashes"], correctAnswer: 1 },
            { id: 9, question: "Which type of malware encrypts victim files and demands payment?", options: ["Trojan", "Spyware", "Ransomware", "Adware"], correctAnswer: 2 },
            { id: 10, question: 'What is the purpose of a "payload" in exploitation?', options: ["A network scan result", "Code that executes on the target after exploitation", "A firewall rule", "A decoy system"], correctAnswer: 1 },
            { id: 11, question: 'What is "social engineering" in cybersecurity?', options: ["Writing code exploits", "Manipulating people to reveal confidential information", "Scanning networks for vulnerabilities", "Encrypting data in transit"], correctAnswer: 1 },
            { id: 12, question: "What does the Metasploit Framework primarily provide?", options: ["A network monitoring tool", "A platform for developing and executing exploits", "A password manager", "A firewall configuration tool"], correctAnswer: 1 },
            { id: 13, question: 'What is "fuzzing" used for in security testing?', options: ["Cracking encrypted passwords", "Sending malformed inputs to find crashes/vulnerabilities", "Monitoring outbound traffic", "Configuring IDS rules"], correctAnswer: 1 },
            { id: 14, question: "Which attack floods a target with traffic to make it unavailable?", options: ["Phishing", "SQL Injection", "Distributed Denial of Service (DDoS)", "ARP Poisoning"], correctAnswer: 2 },
            { id: 15, question: "What is ARP Poisoning used for?", options: ["Encrypting network traffic", "Redirecting traffic by corrupting the ARP cache", "Blocking malicious ports", "Cracking Wi-Fi passwords"], correctAnswer: 1 },
            { id: 16, question: 'What is a "reverse shell"?', options: ["A shell that runs backwards", "A connection initiated by the target back to the attacker", "A shell used to reverse engineer code", "A backup command prompt"], correctAnswer: 1 },
            { id: 17, question: "What does OSINT stand for?", options: ["Offensive Security Intelligence Network Tool", "Open Source Intelligence", "Online Security Intrusion Notification Tool", "Operational System Inspection"], correctAnswer: 1 },
            { id: 18, question: "Which Wi-Fi attack captures the 4-way handshake to crack a WPA2 password?", options: ["Evil Twin Attack", "Deauthentication + Handshake Capture", "Packet Injection", "Wardriving"], correctAnswer: 1 },
            { id: 19, question: 'What is a "honeypot" in security assessment?', options: ["A tool for cracking passwords", "A decoy system designed to attract and study attackers", "A type of malware", "A VPN endpoint"], correctAnswer: 1 },
            { id: 20, question: "What does CVE stand for?", options: ["Common Vulnerability Enumeration", "Cyber Vulnerability Exploit", "Common Vulnerabilities and Exposures", "Critical Vulnerability Entry"], correctAnswer: 2 }
        ],
        defensive: [
            { id: 1, question: "What is the main purpose of a SIEM system?", options: ["Encrypt stored data", "Aggregate and analyze security logs for threat detection", "Block malicious websites", "Scan for open ports"], correctAnswer: 1 },
            { id: 2, question: 'What does "defense in depth" mean?', options: ["Using the strongest single security control", "Layering multiple security controls so one failure doesn't compromise the system", "Hiding servers behind a firewall", "Encrypting all data at rest"], correctAnswer: 1 },
            { id: 3, question: "What is an Intrusion Detection System (IDS)?", options: ["A system that blocks all inbound traffic", "A system that monitors traffic and alerts on suspicious activity", "A firewall that encrypts packets", "A VPN concentrator"], correctAnswer: 1 },
            { id: 4, question: "What is the difference between IDS and IPS?", options: ["IDS is faster than IPS", "IPS can actively block threats; IDS only alerts", "IDS encrypts traffic; IPS decrypts it", "They are identical"], correctAnswer: 1 },
            { id: 5, question: 'What is a "security baseline"?', options: ["The minimum acceptable level of security configuration for a system", "The maximum allowed bandwidth", "The first line of network defense", "A type of firewall rule"], correctAnswer: 0 },
            { id: 6, question: '"What does "patch management" involve?"', options: ["Replacing old hardware", "Systematically applying updates to fix software vulnerabilities", "Configuring firewall rules", "Conducting penetration tests"], correctAnswer: 1 },
            { id: 7, question: "What is Multi-Factor Authentication (MFA)?", options: ["Using a very long password", "Requiring two or more verification factors to grant access", "Logging in from multiple devices", "Using multiple firewalls"], correctAnswer: 1 },
            { id: 8, question: "What is the principle of least privilege?", options: ["Giving users the minimum permissions needed for their job", "Restricting physical access to servers", "Encrypting all communications", "Scanning for vulnerabilities weekly"], correctAnswer: 0 },
            { id: 9, question: "What is a Security Operations Center (SOC)?", options: ["A room with security cameras", "A team/facility monitoring, detecting, and responding to security incidents", "A software firewall", "A compliance reporting tool"], correctAnswer: 1 },
            { id: 10, question: "What does 'threat intelligence' provide?", options: ["Automatic patch deployment", "Actionable information about current and emerging threats", "Network traffic encryption", "User activity monitoring"], correctAnswer: 1 },
            { id: 11, question: "What is a digital forensics investigation used for?", options: ["Recovering deleted files for personal use", "Collecting and analyzing evidence of security incidents or crimes", "Speeding up a slow computer", "Configuring network switches"], correctAnswer: 1 },
            { id: 12, question: "What does 'incident response' involve?", options: ["Installing new hardware", "A structured process for handling security breaches", "Updating antivirus definitions", "Writing security policies"], correctAnswer: 1 },
            { id: 13, question: "What is a WAF (Web Application Firewall)?", options: ["A firewall for blocking all web traffic", "A security tool that filters malicious HTTP traffic to web applications", "A VPN for web developers", "An antivirus for web servers"], correctAnswer: 1 },
            { id: 14, question: "What is Data Loss Prevention (DLP)?", options: ["A backup solution", "Technology that detects and prevents unauthorized data exfiltration", "Encrypting hard drives", "A type of firewall"], correctAnswer: 1 },
            { id: 15, question: 'What does "zero trust" architecture assume?', options: ["All internal traffic is safe", "No user or device is trusted by default, even inside the network", "Only external users are dangerous", "Encryption is unnecessary internally"], correctAnswer: 1 },
            { id: 16, question: "What is the purpose of log management in security?", options: ["To free up disk space", "To store, analyze, and audit system and network activity records", "To speed up application performance", "To configure system backups"], correctAnswer: 1 },
            { id: 17, question: 'What is a "false positive" in IDS alerts?', options: ["A missed real attack", "A legitimate activity incorrectly flagged as malicious", "A correctly detected attack", "A corrupted log entry"], correctAnswer: 1 },
            { id: 18, question: "What is Endpoint Detection and Response (EDR)?", options: ["Antivirus only", "Continuous monitoring and response capabilities on endpoints", "A network packet analyzer", "A cloud backup service"], correctAnswer: 1 },
            { id: 19, question: '"What does "vulnerability management" include?"', options: ["Only scanning for vulnerabilities", "Scanning, prioritizing, remediating, and verifying vulnerabilities continuously", "Blocking all inbound connections", "Encrypting network traffic"], correctAnswer: 1 },
            { id: 20, question: "What is a 'security audit'?", options: ["A penetration test", "A systematic evaluation of security policies, controls, and configurations", "Updating firewall rules", "Monitoring user logins"], correctAnswer: 1 }
        ]
    },
    network: {
        CCNA1: [
            {id:1, question:"What does OSI stand for?", options:["Open System Interconnection","Open Source Interface","Operational System Integration","Original System Instance"], correctAnswer:0},
            {id:2, question:"Which layer is responsible for logical addressing?", options:["Physical Layer","Network Layer","Data Link Layer","Transport Layer"], correctAnswer:1},
            {id:3, question:"Which layer ensures reliable end-to-end communication?", options:["Network Layer","Transport Layer","Session Layer","Physical Layer"], correctAnswer:1},
            {id:4, question:"What is the main function of the Data Link Layer?", options:["Routing","Error detection and framing","Application support","Address resolution"], correctAnswer:1},
            {id:5, question:"What device operates at Layer 2?", options:["Router","Switch","Hub","Firewall"], correctAnswer:1},
            {id:6, question:"Which protocol is connection-oriented?", options:["UDP","TCP","ICMP","ARP"], correctAnswer:1},
            {id:7, question:"What does MAC address stand for?", options:["Media Access Control","Main Access Code","Machine Address Code","Multiple Access Control"], correctAnswer:0},
            {id:8, question:"Which layer encapsulates data into frames?", options:["Application","Transport","Data Link","Network"], correctAnswer:2},
            {id:9, question:"What is the primary purpose of a router?", options:["Forward frames","Forward packets","Connect hosts to LAN","Filter traffic"], correctAnswer:1},
            {id:10, question:"Which protocol resolves IP to MAC address?", options:["ARP","RARP","ICMP","DNS"], correctAnswer:0},
            {id:11, question:"What is the main function of the Physical Layer?", options:["Forward packets","Transmit bits","Error detection","Routing"], correctAnswer:1},
            {id:12, question:"Which layer manages sessions between applications?", options:["Presentation","Session","Transport","Application"], correctAnswer:1},
            {id:13, question:"Which layer encrypts and decrypts data?", options:["Network","Transport","Session","Presentation"], correctAnswer:3},
            {id:14, question:"Which protocol is used for email transmission?", options:["HTTP","SMTP","FTP","DNS"], correctAnswer:1},
            {id:15, question:"What type of address does IP use?", options:["Physical","Logical","Port","Session"], correctAnswer:1}
        ],
        CCNA2: [
            {id:1, question:"What protocol does RIP use for routing updates?", options:["TCP","UDP","ICMP","HTTP"], correctAnswer:1},
            {id:2, question:"What is the default administrative distance of OSPF?", options:["110","120","90","100"], correctAnswer:0},
            {id:3, question:"Which protocol uses port 179 for communication?", options:["RIP","BGP","OSPF","EIGRP"], correctAnswer:1},
            {id:4, question:"Which routing protocol is classless?", options:["RIP v1","RIP v2","IGRP","BGP"], correctAnswer:1},
            {id:5, question:"What is a benefit of link-state routing?", options:["Uses less memory","Faster convergence","Requires no configuration","No IP needed"], correctAnswer:1},
            {id:6, question:"Which protocol is distance-vector?", options:["OSPF","RIP","EIGRP","BGP"], correctAnswer:1},
            {id:7, question:"Which routing protocol supports VLSM?", options:["RIP v1","RIP v2","IGRP","Static Routing"], correctAnswer:1},
            {id:8, question:"What does NAT do?", options:["Maps private IP to public IP","Encrypts traffic","Filters packets","Routes packets"], correctAnswer:0},
            {id:9, question:"Which protocol is used for network time synchronization?", options:["NTP","SNMP","SMTP","HTTP"], correctAnswer:0},
            {id:10, question:"What command shows the routing table on a Cisco router?", options:["show ip route","show route","display ip","get route"], correctAnswer:0},
            {id:11, question:"What is the purpose of HSRP?", options:["Load balancing","High availability","Routing updates","Firewall protection"], correctAnswer:1},
            {id:12, question:"What is a benefit of EIGRP over RIP?", options:["Supports fewer networks","Faster convergence and efficiency","No configuration needed","Uses UDP only"], correctAnswer:1},
            {id:13, question:"Which protocol is link-state?", options:["OSPF","RIP","EIGRP","IGRP"], correctAnswer:0},
            {id:14, question:"Which protocol uses DUAL algorithm?", options:["OSPF","EIGRP","RIP","BGP"], correctAnswer:1},
            {id:15, question:"Which routing protocol uses hop count as metric?", options:["RIP","OSPF","EIGRP","BGP"], correctAnswer:0}
        ],
        CCNA3: [
            {id:1, question:"What is the purpose of VLANs?", options:["To reduce network congestion","To separate broadcast domains","To increase IP addresses","To encrypt data"], correctAnswer:1},
            {id:2, question:"Which protocol provides secure remote management?", options:["Telnet","SSH","HTTP","FTP"], correctAnswer:1},
            {id:3, question:"Which VLAN type carries multiple VLANs between switches?", options:["Access VLAN","Trunk VLAN","Native VLAN","Management VLAN"], correctAnswer:1},
            {id:4, question:"Which protocol is used for dynamic VLAN assignment?", options:["VTP","STP","RIP","OSPF"], correctAnswer:0},
            {id:5, question:"What is the purpose of STP?", options:["Prevent loops in a LAN","Enable routing","Assign IPs","Filter traffic"], correctAnswer:0},
            {id:6, question:"Which address identifies a VLAN?", options:["MAC","IP","VLAN ID","Port number"], correctAnswer:2},
            {id:7, question:"What is the default VLAN on Cisco switches?", options:["VLAN 1","VLAN 10","VLAN 100","VLAN 0"], correctAnswer:0},
            {id:8, question:"Which type of switch port carries traffic for a single VLAN?", options:["Access port","Trunk port","Hybrid port","Management port"], correctAnswer:0},
            {id:9, question:"Which protocol prevents loops in Ethernet networks?", options:["RIP","STP","EIGRP","OSPF"], correctAnswer:1},
            {id:10, question:"Which command shows VLANs on a switch?", options:["show vlan","display vlan","get vlan","list vlan"], correctAnswer:0},
            {id:11, question:"Which feature allows multiple VLANs on one physical link?", options:["Trunking","Access port","Routing","Switchport"], correctAnswer:0},
            {id:12, question:"Which VLAN type is used for management?", options:["VLAN 1","VLAN 10","VLAN 100","VLAN 99"], correctAnswer:3},
            {id:13, question:"Which command sets a port as trunk?", options:["switchport mode trunk","switchport access trunk","switchport trunk enable","port trunk mode"], correctAnswer:0},
            {id:14, question:"Which protocol carries VLAN information between switches?", options:["STP","VTP","RIP","OSPF"], correctAnswer:1},
            {id:15, question:"Which protocol provides secure VLAN management?", options:["HTTP","HTTPS","Telnet","FTP"], correctAnswer:1}
        ]
    },
    programming: {
        C_programming: [
            {id:1, question:"Which operator is used for logical AND in C?", options:["&&","||","&","|"], correctAnswer:0},
            {id:2, question:"What is the correct way to declare an integer array of size 5?", options:["int arr[5];","int arr;","arr[5] int;","array int[5];"], correctAnswer:0},
            {id:3, question:"Which function is used to print in C?", options:["printf()","print()","cout","write()"], correctAnswer:0},
            {id:4, question:"Which header file contains printf()?", options:["stdio.h","conio.h","stdlib.h","string.h"], correctAnswer:0},
            {id:5, question:"Which operator is used to access a pointer's value?", options:["*","&","->","%"], correctAnswer:0},
            {id:6, question:"What is the size of int in C (on 32-bit system)?", options:["2 bytes","4 bytes","8 bytes","Depends on compiler"], correctAnswer:1},
            {id:7, question:"Which loop executes at least once?", options:["for","while","do-while","foreach"], correctAnswer:2},
            {id:8, question:"Which symbol is used for single-line comments?", options:["//","/*","#","--"], correctAnswer:0},
            {id:9, question:"Which keyword is used for constant values?", options:["const","final","static","immutable"], correctAnswer:0},
            {id:10, question:"Which function reads formatted input?", options:["scanf()","read()","input()","cin"], correctAnswer:0},
            {id:11, question:"Which operator is used for bitwise OR?", options:["|","||","&","&&"], correctAnswer:0},
            {id:12, question:"Which operator is used for modulus?", options:["%","/","*","$"], correctAnswer:0},
            {id:13, question:"Which keyword declares a function prototype?", options:["void","int","return","All of the above"], correctAnswer:3},
            {id:14, question:"Which operator increments a variable by 1?", options:["++","--","+","+="], correctAnswer:0},
            {id:15, question:"Which function terminates a program?", options:["exit()","stop()","terminate()","quit()"], correctAnswer:0}
        ],
        Python: [
            {id:1, question:"Which keyword is used to define a function in Python?", options:["function","def","func","lambda"], correctAnswer:1},
            {id:2, question:"What is the output of len('Hello')?", options:["4","5","6","Error"], correctAnswer:1},
            {id:3, question:"Which of these is a mutable data type?", options:["tuple","list","string","int"], correctAnswer:1},
            {id:4, question:"What keyword is used to handle exceptions?", options:["try","catch","except","final"], correctAnswer:2},
            {id:5, question:"Which symbol is used for single-line comments?", options:["#","//","/*","--"], correctAnswer:0},
            {id:6, question:"Which keyword is used for inheritance?", options:["extends","inherits","class","super"], correctAnswer:2},
            {id:7, question:"How do you import a module?", options:["include module","import module","require module","use module"], correctAnswer:1},
            {id:8, question:"Which function returns type of variable?", options:["typeof()","type()","class()","kind()"], correctAnswer:1},
            {id:9, question:"Which keyword creates anonymous functions?", options:["lambda","def","func","anonymous"], correctAnswer:0},
            {id:10, question:"Which method adds element to list?", options:["append()","add()","push()","insert()"], correctAnswer:0},
            {id:11, question:"Which keyword is used to define a class?", options:["class","def","object","struct"], correctAnswer:0},
            {id:12, question:"Which function returns maximum value?", options:["max()","min()","largest()","high()"], correctAnswer:0},
            {id:13, question:"Which keyword defines a block of code with no operation?", options:["pass","null","void","none"], correctAnswer:0},
            {id:14, question:"Which operator is used for exponentiation?", options:["**","^","exp","pow()"], correctAnswer:0},
            {id:15, question:"Which keyword exits a loop immediately?", options:["break","exit","stop","continue"], correctAnswer:0}
        ],
        HTML: [
            {id:1, question:"Which tag is used to create a hyperlink?", options:["<a>","<link>","<href>","<hyper>"], correctAnswer:0},
            {id:2, question:"Which tag defines the largest heading?", options:["<h1>","<h6>","<head>","<heading>"], correctAnswer:0},
            {id:3, question:"Which attribute defines image source?", options:["src","href","link","img"], correctAnswer:0},
            {id:4, question:"Which tag is for table rows?", options:["<tr>","<td>","<th>","<table>"], correctAnswer:0},
            {id:5, question:"Which tag is for table data?", options:["<td>","<tr>","<th>","<table>"], correctAnswer:0},
            {id:6, question:"Which tag adds a line break?", options:["<br>","<hr>","<lb>","<break>"], correctAnswer:0},
            {id:7, question:"Which tag is used for bold text?", options:["<b>","<strong>","<i>","Both A and B"], correctAnswer:3},
            {id:8, question:"Which tag is for italic text?", options:["<i>","<em>","<italic>","Both A and B"], correctAnswer:3},
            {id:9, question:"Which tag contains metadata?", options:["<meta>","<head>","<body>","<info>"], correctAnswer:0},
            {id:10, question:"Which attribute specifies CSS classes?", options:["class","id","style","type"], correctAnswer:0},
            {id:11, question:"Which tag is for ordered list?", options:["<ol>","<ul>","<li>","<list>"], correctAnswer:0},
            {id:12, question:"Which tag is for unordered list?", options:["<ul>","<ol>","<li>","<list>"], correctAnswer:0},
            {id:13, question:"Which attribute specifies inline style?", options:["style","class","id","css"], correctAnswer:0},
            {id:14, question:"Which tag is for paragraph?", options:["<p>","<para>","<text>","<paragraph>"], correctAnswer:0},
            {id:15, question:"Which tag is for comment?", options:["<!-- -->","//","/* */","#"], correctAnswer:0}
        ],
        CSS: [
            {id:1, question:"Which property changes text color in CSS?", options:["color","font-color","text-color","background-color"], correctAnswer:0},
            {id:2, question:"How do you select an element with id='main' in CSS?", options:["#main",".main","*main","main"], correctAnswer:0},
            {id:3, question:"Which property changes background color?", options:["background-color","color","bgcolor","background"], correctAnswer:0},
            {id:4, question:"Which property changes font size?", options:["font-size","text-size","size","font-style"], correctAnswer:0},
            {id:5, question:"Which property makes text bold?", options:["font-weight","text-weight","font-style","text-style"], correctAnswer:0},
            {id:6, question:"Which unit is relative to the parent font size?", options:["em","px","pt","cm"], correctAnswer:0},
            {id:7, question:"Which selector targets all elements?", options:["*","body","html",".all"], correctAnswer:0},
            {id:8, question:"Which property aligns text?", options:["text-align","align","vertical-align","text-position"], correctAnswer:0},
            {id:9, question:"Which property sets element width?", options:["width","size","length","dimension"], correctAnswer:0},
            {id:10, question:"Which property sets element height?", options:["height","size","length","dimension"], correctAnswer:0},
            {id:11, question:"Which property adds space inside an element?", options:["padding","margin","spacing","border"], correctAnswer:0},
            {id:12, question:"Which property adds space outside an element?", options:["margin","padding","spacing","border"], correctAnswer:0},
            {id:13, question:"Which property controls element display type?", options:["display","visibility","position","float"], correctAnswer:0},
            {id:14, question:"Which property positions elements relative to the viewport?", options:["position","display","float","top"], correctAnswer:0},
            {id:15, question:"Which property changes text decoration?", options:["text-decoration","font-decoration","text-style","font-style"], correctAnswer:0}
        ],
        JavaScript: [
            {id:1, question:"Which keyword declares a block-scoped variable?", options:["var","let","const","All of the above"], correctAnswer:1},
            {id:2, question:"What is the output of typeof [] in JavaScript?", options:["array","object","list","undefined"], correctAnswer:1},
            {id:3, question:"Which operator is for strict equality?", options:["==","===","=","!="], correctAnswer:1},
            {id:4, question:"Which method adds elements to the end of array?", options:["push()","pop()","shift()","unshift()"], correctAnswer:0},
            {id:5, question:"Which method removes the last element from array?", options:["pop()","push()","shift()","unshift()"], correctAnswer:0},
            {id:6, question:"Which keyword defines a function?", options:["function","def","func","lambda"], correctAnswer:0},
            {id:7, question:"Which object stores key-value pairs?", options:["Map","Object","Array","Set"], correctAnswer:0}
        ]
    }
};